### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by renjinsk** [pascal-zarrad/tc-discord-webhooks#2]
Problem: Look's like no messages are sent

TeamCity Version: 2019.2.1 (build 71758)
Settings as displayed at the screenshot.

![Screenshot from 2020-02-07 10-57-04](https://user-images.githubusercontent.com/456717/74015316-0b804100-4999-11ea-89e5-f3d1857d9e7b.png)

**Comment by pascal-zarrad** [comment]
I tried to reproduce your error using the same settings (if I didn't miss anything) as your screenshot shows. I was unable to reproduce the problem, as all messages were successfully send to my test webhook.

I used TeamCity 2019.2.1 for my testing.

My TeamCity configuration that I used for testing:
![image](https://user-images.githubusercontent.com/14060618/74567620-7e2f8480-4f76-11ea-90d6-cfe40021579b.png)
Note that I did not check "Builds with my changes only" and "My favorite builds only". I'm unable to see the state of those settings on your screenshot. I simply put my webhook URL in the "WebHook URL" field an used the same Username as you.


The result of my test:
![image](https://user-images.githubusercontent.com/14060618/74567578-68ba5a80-4f76-11ea-9ee6-a9d8a07fc19b.png)


Please leave a comment if you solved the problem in the meantime.
If you did not solve the probem, please provide further information about the problem (Screenshot showing the part of your TC Discord WebHook configuration that cannot be seen on the current sscreenshot; list of the plugins you're using, ...).

**Comment by renjinsk** [comment]
Sorry for the late response.
About the missing part in the screenshot:
**Builds with my changes only** is unchecked
 **My favorite builds only** is unchecked

Teamcity is hosted in AWS, created by the cloudformation template they provide.

**Comment by pascal-zarrad** [comment]
@renjinsk Your settings look good and should work. Maybe it is some problem with AWS / AWS with the cloudformation template.
Unfortunately, I'm currently unable to test this plugin on AWS to find out the cause of the problem.
