### ISSUE TITLE
include changes in notification (commit log)

### ISSUE THREAD

**Issue by frnandu** [pascal-zarrad/tc-discord-webhooks#20]
**Is your feature request related to a problem? Please describe.**
Would be nice to have info on what changes the build includes

**Describe the solution you'd like**
shoudl be possible to get the list of changes (commit msg log) and include it on the notification

**Comment by pascal-zarrad** [comment]
@frnandu This is a good idea and I think this could be a new feature. I'm not sure if this should be implemented before #11 has been implemented, as you should be able to enable and disable the commit log.

I would either implement it during #11 or afterwards as an own functionality.
