### ISSUE TITLE
If branch filter is set to all branches, correct branch is not reported by the message

### ISSUE THREAD

**Issue by Licho1** [pascal-zarrad/tc-discord-webhooks#3]
1) set the branch filter to +:*

-> you expect to have branch name in  notifications
Instead notification looks like this:

Build succeeded!
The build with the ID 41167 has succeeded!
Project:
ZenID
Build:
Demo deploy
Branch
Default

With branch == Default

**Comment by pascal-zarrad** [comment]
The bugs existance has been verified. PR provided by creator of the issue.
