### ISSUE TITLE
Missing settings in Notification Rules

### ISSUE THREAD

**Issue by ProtoCorey** [pascal-zarrad/tc-discord-webhooks#35]
**Describe the bug**

When attempting to assign a hook in Notification Rules -> Discord WebHook, no settings box appears to be able to assign the hook or username. You can see the normal "watching" rules box, but no settings for this tool. 

**To Reproduce**
1.  Install Webhook Plugin
2. Restart Server
3. Go to Groups -> Notification Rules -> Discord WebHook
4. Notice the settings box is missing

**Expected behavior**
Should have settings box for hook url and username visible and able to be edited 

**Screenshots**
![image](https://user-images.githubusercontent.com/82787716/162876482-91561042-9510-4b58-a520-eedec4768dcd.png)

**Environment:**
 - OS: Windows 10

**Comment by pascal-zarrad** [comment]
Hi, I will look into your issue sometime during the next days.

**Comment by pascal-zarrad** [comment]
Hi @ProtoCorey 

Right now you cannot set a specific webhook for a group, you can only configure the notification rules.
Those rules will be inherited by the users of the group. The users can then define a webhook.

> A workaround would be to just use the group leader to configure notifications.

As there is a suitable workaround, I wont implement a feature to specify a dedicated webhook in groups, as I don't think it makes much sense. Creating inherited notification rules is a great feature. But specifying the notifications is more on the user side and is standard for TC. If you check the other notificators (email, browser, slack, etc.) you won't find their connection configuration on the groups page either, as the settings page is only made for configuring rules that will be inherited.

What maybe would make more sense is the possibility to specify webhooks on a project level, as group level can be solved using an user account that handles the notification.
Unfortunately, implementing such a feature would take too much time for me.

Feel free to implement one of the features if you'd like to!

**Comment by pascal-zarrad** [comment]
As there was no response until now, I assume my last comment resolved the issue for now.
